// React/src/components/PlayGame.js
import {useEffect, useState} from 'react';
import { Link, useNavigate } from "react-router-dom";
import "./Game.css";
import felt from "../images/greenfelt.png"

export default function PlayGame() {
  const [data, setData] = useState("");
  let navigate = useNavigate();
  const startGame = async () => {
    const resp = await fetch('http://localhost:8080/startGame/p');
    const json = await resp.json();
    setData(json);
  }

  const drawCard = async () => {
    const resp = await fetch('http://localhost:8080/draw');
    const json = await resp.json();
    setData(json);
    if(json.gameOver){
      navigate("/game-over");
    }
  }

  useEffect(() => {
    startGame();
  }, []);

  return (
    <div>
      <ul id="stats">
      <li>Round: {data.round}</li>
      <li>Wars: {data.warCount}</li>
      <li>You have shuffled your cards {data.playerShuffleCount} times</li>
      <li>The computer has shuffled its cards {data.computerShuffleCount} times</li>
    </ul>
    <section id="table" style={{ backgroundImage: `url(${felt})`, backgroundRepeat: "no-repeat" }}>
      <p id="computer-hand" className="hand">The computer has {data.computerHandCount} cards</p>
      <section id="cards">
      <PlayingCard rank={data.computerRank} suit={data.computerSuit} flip="true" />
      <PlayingCard rank={data.playerRank} suit={data.playerSuit} flip="" />
      </section>
      
      <p id="user-hand" className="hand">You have {data.playerHandCount} cards</p>
    </section>
    <p id="output">{data.outcome}</p>
    <section className="button-group">
      <button className="small button green" onClick={drawCard}>Draw Card</button>
      <Link to="/game-over" className="small button red">Give Up</Link>
    </section>
  </div>
  )
}

function PlayingCard(props) {
  const suit = props.suit;
  if (suit === "H") {
    return <div class="card red-card">
      <p className="top">{props.rank}</p>
      <span class={`suit ${props.flip ? "flip" : ""}`}>&#9829;</span>
      <p className="bottom">{props.rank}</p>
    </div>
  }
  if (suit === "S") {
    return <div class="card">
      <p className="top">{props.rank}</p>
      <span class={`suit ${props.flip ? "flip" : ""}`}>&#9824;</span>
      <p className="bottom">{props.rank}</p>
    </div>
  }
  if (suit === "C") {
    return <div class="card">
      <p className="top">{props.rank}</p>
      <span class={`suit ${props.flip ? "flip" : ""}`}>&#9827;</span>
      <p className="bottom">{props.rank}</p>
    </div>
  }
  if (suit === "D") {
    return <div class="card red-card">
      <p className="top">{props.rank}</p>
      <span class={`suit ${props.flip ? "flip" : ""}`}>&#9830;</span>
      <p className="bottom">{props.rank}</p>
    </div>
  }
  if (suit === "f") {
    return <div class="card red-card">
      <p className="top">{props.rank}</p>
      <p className="bottom">{props.rank}</p>
    </div>
  }
}

// Angular/src/app/play-game/play-game.component.ts
import { Component, OnInit } from '@angular/core';
import { Card } from '../deck/card.model';
import { GameService } from '../game.service';
import { RoundOutcome } from '../round-outcome.model';

@Component({
  selector: 'app-play-game',
  templateUrl: './play-game.component.html',
  styleUrls: ['./play-game.component.css']
})
export class PlayGameComponent implements OnInit {
  roundOutcome: RoundOutcome = new RoundOutcome('',0,0,new Card(0,''),new Card(0,''),0,0,0,0,false);
  inWar: boolean = false;
  cardsDrawnForWar: number = 0;
  roundOfWar = 0;

  constructor(private gameService: GameService) {}

  ngOnInit() {
    this.gameService.roundOutcome.subscribe((outcome: RoundOutcome)=>{
      this.roundOutcome = outcome;
    });
    this.gameService.inWar.subscribe((inWar: boolean)=>{
      this.inWar = inWar;
    })
  }

  draw() {
    this.gameService.drawCard();
    this.cardsDrawnForWar = 0;
  }

  checkSuit(suit: string):boolean {
    if(suit==='♥' || suit==='♦') {
      return true;
    }
    return false;
  }

  drawForWar() {
    if(this.cardsDrawnForWar===4){
      this.cardsDrawnForWar = 0;
    }
    if(this.cardsDrawnForWar===3){
      this.gameService.drawCard();
      this.cardsDrawnForWar++;
    } else {
      this.cardsDrawnForWar++;
    }
  }
}

<ul id="game-stats">
    <li><h2>Round: {{roundOutcome.roundNumber}}</h2></li>
    <li><h2>Wars: {{roundOutcome.warCount}}</h2></li>
</ul>

<p></p>
<p id="copmuter-stats">The computer has {{roundOutcome.computerHandCount}} card{{roundOutcome.computerHandCount===1 ? '':'s'}}. It shuffled it's deck {{roundOutcome.computerShuffleCount}} time{{roundOutcome.computerShuffleCount===1 ? '' : 's'}}.</p>
<section id="table">
    <div *ngIf="roundOutcome.computerCard.rank!=0">
        <div 
        id="computer-card" 
        [ngClass]="checkSuit(roundOutcome.computerCard.suit) ? 'red': ''" 
        *ngIf="cardsDrawnForWar===0 || cardsDrawnForWar===4"
        >
            <span class="top">{{roundOutcome.computerCard.getRank()}}</span>
            <span class="suit">{{roundOutcome.computerCard.suit}}</span>
            <span class="bottom">{{roundOutcome.computerCard.getRank()}}</span>
    </div>
    <div class="war-card" id="computer-war-1" *ngIf="cardsDrawnForWar>2"></div>
    <div class="war-card" id="computer-war-2" *ngIf="cardsDrawnForWar>1"></div>
    <div class="war-card" id="computer-war-3" *ngIf="cardsDrawnForWar>0"></div>
    <div 
        id="player-card" 
        [ngClass]="checkSuit(roundOutcome.playerCard.suit) ? 'red': ''" 
        *ngIf="cardsDrawnForWar===0 || cardsDrawnForWar===4"
        >
            <span class="top">{{roundOutcome.playerCard.getRank()}}</span>
            <span class="suit">{{roundOutcome.playerCard.suit}}</span>
            <span class="bottom">{{roundOutcome.playerCard.getRank()}}</span>
    </div>
    <div class="war-card" id="player-war-1" *ngIf="cardsDrawnForWar>2"></div>
    <div class="war-card" id="player-war-2" *ngIf="cardsDrawnForWar>1"></div>
    <div class="war-card" id="player-war-3" *ngIf="cardsDrawnForWar>0"></div>
    </div>
</section>
<p id="player-stats">You have {{roundOutcome.playHandCount}} card{{roundOutcome.playHandCount===1 ? '':'s'}}. You have shuffled your deck {{roundOutcome.playerShuffleCount}} time{{roundOutcome.playerShuffleCount===1 ? '' : 's'}}.</p>
<p [ngClass]="inWar ? 'message war-alert' : 'message'"><i class="fa-solid fa-triangle-exclamation" *ngIf="inWar"></i> {{roundOutcome.message}} <i class="fa-solid fa-triangle-exclamation" *ngIf="inWar"></i></p>

<section class="btn-group" *ngIf="!inWar">
    <button (click)="draw()" class="btn btn-green size-20 half">Draw Card</button>
    <button routerLink="/game-over" class="btn btn-red size-20 half">Give Up</button>
</section>
<section class="btn-group" *ngIf="inWar">
    <button class="btn size-20 btn-red full" (click)="drawForWar()">Draw Cards for War</button>
</section>
